name: Build LaTeX PDF

on:
  push:
    paths:
      - 'doc/aspdac2026/**'
  pull_request:
    paths:
      - 'doc/aspdac2026/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up TeX Live
        uses: xu-cheng/latex-action@v3
        with:
          root_file: doc/aspdac2026/main.tex

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: aspdac2026-pdf
          path: doc/aspdac2026/main.pdf
